{"360 Degree Feedback":["Human Resource","Performance Appraisal","Survey","Talent Management"],
"3D Architecture":["3D CAD","Architectural CAD","Architecture","BIM","Home Builder"],
"3D CAD":["3D Architecture","Architectural CAD","Engineering CAD","Simulation"],
"AB Testing":["Campaign Management","Landing Page","Web Analytics"],
"AML":["Banking Systems","Compliance","Financial Fraud Detection","Financial Risk Management","Risk Management"],
"API Management,Integration,
"Account Based Marketing":["Lead Generation","Marketing Automation","Personalization"],
"Accounting":["Accounting Practice Management","Accounts Payable","Accounts Receivable","Audit","Auto Dealer Accounting","Billing and Invoicing","Budgeting","Compliance","Debt Collection","Financial Reporting","Fund Accounting","Sales Tax","Trust Accounting"],
"Accounting Practice Management":["Accounting","Accounts Payable","Accounts Receivable","Auto Dealer Accounting","Bookkeeper","Church Accounting","Construction Accounting","Financial Reporting","Financial Services","Fund Accounting","Lease Accounting","Nonprofit Accounting","Professional Services Automation","Sales Tax","School Accounting","Tax Practice Management","Trust Accounting"],
"Accounts Payable":["Accounting","Accounting Practice Management","Accounts Receivable","Billing and Invoicing"],
"Accounts Receivable":["Accounting","Accounting Practice Management","Accounts Payable","Billing and Invoicing"],
"Accreditation Management":["Compliance","Document Management","Higher Education"],
"Ad Server":["Campaign Management","Marketing Automation"],
"Admissions":["Scholarship Management","School Administration"],
"Advertising Agency":["Campaign Management","Professional Services Automation","Project Management"],
"Advocacy":["Customer Engagement","Employee Engagement","Political Campaign","Referral"],
"Affiliate":["Referral","eCommerce"],
"Agile Project Management Tools":["App Design","Application Development","DevOps","Game Development","IT Project Management","Kanban Tools","Project Management","Project Portfolio Management","Project Tracking","Scrum"],
"Airline Reservation System":["Reservations","Travel Agency"],
"Alumni Management":["Association Management","Club Management","Membership Management"],
"Android Kiosk":["Digital Signage","Kiosk","Order Entry","Photo Booth","Ticketing","iPad Kiosk"],
"Animal Shelter":["Kennel","Pet Grooming","Pet Sitting","Zoo"],
"Anti-spam":["Computer Security","Email Management","Network Security"],
"App Design":["Application Development","DevOps","Prototyping"],
"Apparel Management":["Enterprise Resource Planning","Fashion Design","Production Scheduling"],
"Applicant Tracking":["Human Resource","Job Board","Onboarding","Performance Appraisal","Recruiting","Reference Check","Talent Management","Video Interviewing"],
"Application Development":["Bug Tracking","Mobility","Product Lifecycle Management","Project Management","VR","Workflow Management"],
"Application Lifecycle Management":["Application Development","Application Performance Management","Product Lifecycle Management","SaaS Management"],
"Application Performance Management":["Application Development","IT Management","Product Lifecycle Management","SaaS Management"],
"Appointment Reminder":["Appointment Scheduling","Customer Communications Management","IVR","SMS Marketing"],
"Appointment Scheduling":["Employee Scheduling","Medical Scheduling","Scheduling"],
"Arborist":["Forestry","Garden Center","Landscape","Utility Management Systems"],
"Architectural CAD":["3D Architecture","3D CAD","Architecture","BIM","Engineering CAD"],
"Architecture":["3D Architecture","3D CAD","Architectural CAD","BIM","Construction Accounting","Construction Estimating","Construction Management","Home Builder","Professional Services Automation"],
"Archiving":["Business Continuity","Compliance","Document Management","Electronic Discovery","Email Archiving"],
"Art Gallery,Museum,
"Artificial Intelligence":["Customer Engagement","Decision Support","Diagram","Game Development","Gamification","Knowledge Management","Live Chat","Predictive Analytics","Robotic Process Automation","Sales Force Automation"],
"Assessment":["Classroom Management","Exam","Learning Management System","Performance Appraisal","Pre-employment Testing","Survey","Talent Management","Training"],
"Asset Tracking":["EAM","Fixed Asset Management","IT Asset Management"],
"Assisted Living":["Human Services","Long Term Care","Patient Case Management"],
"Association Management":["Alumni Management","Fundraising","HOA","Membership Management","Nonprofit"],
"Attendance Tracking":["Employee Scheduling","Human Resource","Payroll","Time Clock"],
"Auction":["Fundraising","eCommerce"],
"Audience Response":["Conference","Event Management","Polling","Survey","Voting"],
"Audit":["Accounting","Compliance","Financial Reporting","Financial Risk Management","Risk Management"],
"Augmented Reality":["Application Development","Game Development","Learning Experience Platform","Training","VR","Virtual Tour"],
"Authentication":["Computer Security","Identity Management","Network Security"],
"Auto Body":["Auto Dealer","Auto Dealer Accounting","Auto Repair"],
"Auto Dealer":["Auto Body","Auto Dealer Accounting","Auto Repair"],
"Auto Dealer Accounting":["Accounting","Accounting Practice Management","Auto Body","Auto Dealer","Auto Repair"],
"Auto Dialer":["Appointment Reminder","Call Center","Inside Sales","Predictive Dialer","Telemarketing"],
"Auto Repair":["Auto Body","Auto Dealer","Auto Dealer Accounting"],
"Automated Testing":["Application Development","Bug Tracking","Quality Management","Requirements Management"],
"Aviation Maintenance":["Equipment Maintenance","Fleet Maintenance","Maintenance Management"],
"BIM":["3D Architecture","3D CAD","Architectural CAD","Architecture","Construction Management","Engineering CAD"],
"Background Check":["Applicant Tracking","Human Resource","Pre-employment Testing","Recruiting","Recruiting Agency","Reference Check"],
"Backup":["Business Continuity","Data Loss Prevention","Disk Imaging","File Sharing","File Sync","Server Backup","Virtual Machine"],
"Bakery":["Food Service Distribution","Food Service Management","Nutrition Analysis","Restaurant Management","Restaurant POS"],
"Banking Systems":["Financial Risk Management","Investment Management","Loan Origination","Loan Servicing","Mobile Banking"],
"Bankruptcy":["Debt Collection","Docketing","Forms Automation","Law Practice Management","Legal Billing","Legal Calendar","Legal Case Management","Legal Document Management"],
"Bar POS":["Point of Sale","Restaurant POS","iPad POS"],
"Barbershop,Salon,
"Barcoding":["Inventory Control","Inventory Management","Shipping"],
"Benefits Administration":["Claims Processing","Corporate Wellness","Employee Communication Tools","Employee Engagement","Employee Recognition","Ergonomics","Human Resource","Payroll"],
"Big Data":["Business Intelligence","Dashboard","Data Visualization"],
"Billing and Invoicing":["Accounting","Accounts Receivable","Debt Collection","Expense Report","Legal Billing","Medical Billing","Time and Expense"],
"Billing and Provisioning":["Telecom Expense Management","Telephony","Wireless Expense Management"],
"Blog":["Content Management","Content Marketing","SEO","Website Builder"],
"Board Management":["File Sharing","Meeting","Portal","Reporting","Scheduling","Web Conferencing"],
"Bookkeeper":["Accounting","Accounting Practice Management","Financial Reporting","Sales Tax"],
"Brand Management":["Campaign Management","Digital Asset Management","Marketing Automation"],
"Brand Protection":["Brand Management","Digital Asset Management","Digital Rights Management"],
"Brewery":["Farm Management","Point of Sale","Retail Management Systems","Winery","iPad POS"],
"Budgeting":["Accounting","Business Performance Management","Compliance","Financial Reporting"],
"Bug Tracking":["Application Development","Application Lifecycle Management","Issue Tracking","Product Lifecycle Management","Quality Management"],
"Building Maintenance":["Equipment Maintenance","Field Service Management","HVAC","Maintenance Management","Service Dispatch","Work Order"],
"Business Card":["Graphic Design","Web to Print"],
"Business Continuity":["Database Management","IT Management","Network Monitoring","Website Monitoring"],
"Business Intelligence":["Dashboard","Data Visualization","Decision Support","Embedded Analytics","Heatmap","Reporting","Risk Management","Text Mining","Web Analytics"],
"Business Management":["Accounting","Budgeting","Customer Relationship Management","Enterprise Resource Planning","Human Resource","Project Management"],
"Business Performance Management":["Budgeting","Business Intelligence","Decision Support","Financial Reporting","Reporting"],
"Business Phone Systems":["Cloud PBX","Telephony","Unified Communications","VoIP"],
"Business Plan":["Business Management","Business Performance Management"],
"Business Process Management":["Forms Automation","Robotic Process Automation","Workflow Management"],
"CMDB":["Change Management","ITSM","Quality Management"],
"CMMS":["Aviation Maintenance","Building Maintenance","Calibration Management","Equipment Maintenance","Facility Management","Fleet Maintenance","Maintenance Management"],
"CPQ":["Job Costing","Product Configurator","Proposal Management","Quoting","Sales Force Automation"],
"Calibration Management":["CMMS","Maintenance Management"],
"Call Accounting":["Billing and Provisioning","Call Recording","Telecom Expense Management","Telephony","Wireless Expense Management"],
"Call Center":["Call Recording","Customer Relationship Management","Customer Service","Help Desk","IVR","Online CRM","Telephony"],
"Call Recording":["Call Accounting","Call Center","IVR","Telecom Expense Management","Telephony","Wireless Expense Management"],
"Call Tracking":["Business Intelligence","Call Center","Campaign Management","Lead Management","Reporting","Sales Force Automation"],
"Camp Management":["Parks and Recreation","Registration"],
"Campaign Management":["AB Testing","Brand Management","Email Marketing","Marketing Automation","Survey","Web Analytics"],
"Campground Management":["Camp Management","Reservations","Vacation Rental"],
"Car Rental":["Fleet Management","Rental"],
"Carpet Cleaning":["Appointment Scheduling","Billing and Invoicing","Employee Scheduling","Field Service Management","Janitorial","Maid Service","Route Planning","Service Dispatch"],
"Catalog Management":["Order Entry","Order Management","Product Configurator","Publishing and Subscriptions","eCommerce"],
"Catering":["Event Management","Food Service Distribution","Food Service Management","Nutrition Analysis","Restaurant Management","Restaurant POS"],
"Cemetery,Funeral Home,
"Change Management":["CMDB","ITSM","Quality Management"],
"Channel Management":["Campaign Management","Lead Management","Marketing Automation"],
"Chemical":["MRP","Simulation"],
"Child Care,School Administration,
"Chiropractic":["Electronic Medical Records","Medical Billing","Medical Practice Management","Medical Scheduling","Medical Transcription","Patient Case Management","Patient Management"],
"Church Accounting":["Accounting","Accounting Practice Management","Church Management","Fund Accounting","Nonprofit"],
"Church Management":["Church Accounting","Donation Management","Membership Management","Nonprofit"],
"Church Presentation":["Church Management","Worship"],
"Claims Processing":["Benefits Administration","Commercial Insurance","Insurance Agency","Insurance Policy","Insurance Rating","Medical Billing"],
"Class Registration":["Dance Studio","Driving School","Higher Education","K-12","Martial Arts","Pilates Studio","Registration","Swim School","Tutoring","Yoga Studio"],
"Classroom Management":["Course Authoring","Gradebook","School Administration"],
"Click Fraud":["Campaign Management","PPC","Web Analytics"],
"Clinical Trial Management":["Hospital Management","Medical Lab"],
"Cloud Communication Platform":["Cloud PBX","Softphone","Team Communication","Telephony","Unified Communications","Web Conferencing"],
"Cloud Management,Server Management,
"Cloud PBX":["Business Phone Systems","Telephony","Unified Communications","VoIP"],
"Cloud Security":["Anti-spam","Business Continuity","Computer Security","Cybersecurity","Email Security","Network Monitoring","Network Security","Network Troubleshooting","Vulnerability Management"],
"Cloud Storage":["Backup","Cloud Management","File Sharing","File Sync"],
"Club Management":["Dance Studio","Fitness","Golf Course","Martial Arts","Membership Management","Parks and Recreation","Personal Trainer","Pilates Studio","Yoga Studio"],
"Coaching":["Business Management","Mentoring","Professional Services Automation","Sales Coaching","Tutoring"],
"Code Enforcement":["Compliance","Government"],
"Collaboration":["Community","Project Management","Social Networking","Web Conferencing"],
"Commercial Insurance":["Claims Processing","Insurance Agency","Insurance Policy","Insurance Rating","P&C Insurance"],
"Commercial Loan":["Banking Systems","Financial Risk Management","Loan Origination","Loan Servicing"],
"Commercial Real Estate":["Real Estate Agency","Real Estate CMA","Real Estate CRM","Real Estate Property Management","Real Estate Transaction Management"],
"Commission":["Compensation Management","Contract Management","Payroll"],
"Community":["Collaboration","Knowledge Management","Social Networking"],
"Company Secretarial":["Accounting","Board Management","Compliance","Legal Document Management"],
"Compensation Management":["Commission","Human Resource","Payroll","Performance Appraisal","Talent Management"],
"Competitive Intelligence":["Business Intelligence","Reporting"],
"Complaint Management":["Customer Experience","Customer Satisfaction","Customer Service","Help Desk","Issue Tracking"],
"Compliance":["Accounting","Audit","Budgeting","Business Process Management","EHS Management","Environmental","Ergonomics","Financial Reporting","Quality Management"],
"Computer Repair Shop":["Business Management","IT Service"],
"Computer Security":["Endpoint Detection and Response","Network Monitoring","Network Security","Website Monitoring"],
"Conference":["Catering","Event Check In","Event Management","Meeting","Registration","Ticketing","Venue Management","Web Conferencing","Webinar"],
"Conflict Checking":["Law Practice Management","Legal Billing","Legal Case Management","Legal Document Management"],
"Consignment":["Inventory Control","Point of Sale","Retail Management Systems"],
"Construction Accounting":["Accounting Practice Management","Architecture","Construction CRM","Construction Estimating","Construction Management","Home Builder"],
"Construction Bid Management":["Construction Estimating","Construction Management","Procurement"],
"Construction CRM":["Architecture","Construction Accounting","Construction Estimating","Construction Management","Home Builder"],
"Construction Estimating":["Architecture","Construction Accounting","Construction CRM","Construction Management","Home Builder"],
"Construction Management":["Architecture","Construction Accounting","Construction CRM","Construction Estimating","Home Builder"],
"Construction Scheduling":["Construction Accounting","Construction Bid Management","Construction CRM","Construction Estimating","Construction Management","Employee Scheduling","Residential Construction Estimating","Scheduling"],
"Contact Management":["Customer Relationship Management","Email Marketing","Lead Management","Sales Force Automation"],
"Content Management":["Catalog Management","Content Marketing","Digital Asset Management","Document Management","Java CMS","Knowledge Management","Mobile Content Management System"],
"Content Marketing":["Campaign Management","Content Management","Marketing Automation"],
"Contest":["Campaign Management","Sales Enablement"],
"Continuous Integration":["Application Development","Automated Testing","DevOps","Integration","Vulnerability Management"],
"Contract Management":["Document Management","Forms Automation","Proposal Management","Quoting"],
"Contractor Management,Construction Management,
"Convenience Store":["Point of Sale","Retail Management Systems"],
"Conversational AI Platform":["Artificial Intelligence","Conversational Marketing Platform","Customer Communications Management","Customer Engagement","Deep Learning","Employee Engagement","Lead Generation","Lead Nurturing","Live Chat","Machine Learning","Marketing Automation","Robotic Process Automation","Sales Enablement","Sales Force Automation","Student Engagement Platform"],
"Conversational Marketing Platform":["Account Based Marketing","Artificial Intelligence","Conversational AI Platform","Customer Communications Management","Customer Engagement","Email Marketing","Lead Capture","Lead Generation","Lead Nurturing","Live Chat","Marketing Automation","Mobile Marketing","Personalization","SMS Marketing","Social CRM Tools","Social Selling"],
"Corporate Tax":["Accounting","Accounting Practice Management","Auto Dealer Accounting","Bookkeeper","Church Accounting","Construction Accounting","Nonprofit Accounting","Sales Tax","School Accounting","Tax Practice Management","Trust Accounting"],
"Corporate Wellness":["Benefits Administration","Employee Engagement","Employee Recognition","Ergonomics","Human Resource"],
"Corrective and Preventive Action":["Complaint Management","Compliance","EHS Management","Incident Management","Policy Management","Quality Management","Risk Management","SPC","Sustainability"],
"Courier":["Logistics","Shipping"],
"Course Authoring":["Classroom Management","Learning Experience Platform","Learning Management System","Training","eLearning Authoring Tools"],
"Court Management":["Law Practice Management","Legal Billing","Legal Calendar","Legal Case Management","Legal Document Management"],
"Creative Management":["Advertising Agency","Marketing Automation","Marketing Planning","Video Editing"],
"Credentialing":["Chiropractic","Dental","Hospital Management","Medical Practice Management","Mental Health","Optometry","Pediatric"],
"Currency Exchange,Banking Systems,
"Customer Advocacy":["Advocacy","Customer Loyalty","Influencer Marketing","Referral","Small Business Loyalty Programs"],
"Customer Communications Management":["Content Management","Customer Engagement","Marketing Automation","Personalization"],
"Customer Data Platform":["Data Analysis","Data Warehouse","Marketing Analytics","Marketing Automation","Personalization"],
"Customer Engagement":["Blog","Customer Experience","Customer Loyalty","Customer Relationship Management","Customer Satisfaction","Gamification","Push Notifications"],
"Customer Experience":["Contact Management","Customer Engagement","Customer Loyalty","Customer Relationship Management","Customer Satisfaction","Digital Adoption Platform","Qualitative Data Analysis","Survey"],
"Customer Journey Mapping Tools":["Diagram","Marketing Analytics","Marketing Attribution","Predictive Analytics","UX"],
"Customer Loyalty":["Customer Experience","Customer Relationship Management","Customer Service","Marketing Automation","Small Business Loyalty Programs"],
"Customer Reference Management":["Customer Relationship Management","Lead Management","Referral"],
"Customer Relationship Management":["Contact Management","Lead Management","Marketing Automation","Sales Force Automation"],
"Customer Satisfaction":["Complaint Management","Customer Experience","Customer Loyalty","Customer Service","Help Desk"],
"Customer Service":["Call Center","Complaint Management","Customer Relationship Management","Help Desk","Live Chat","Online CRM"],
"Customer Success":["Customer Engagement","Digital Adoption Platform","Personalization","Predictive Analytics"],
"Cybersecurity":["Anti-spam","Computer Security","Endpoint Detection and Response","Endpoint Protection","Network Security"],
"Dance Studio":["Club Management","Waiver"],
"Dashboard":["Business Intelligence","Business Performance Management","Workflow Management"],
"Data Analysis":["Big Data","Business Intelligence","Qualitative Data Analysis"],
"Data Center Management":["Data Storage","Database Management","IT Management","Network Monitoring","Network Security","Server Management"],
"Data Discovery":["Big Data","Business Intelligence","Data Visualization","Electronic Discovery","Reporting"],
"Data Entry":["Database Management","ETL","Forms Automation","RDBMS"],
"Data Extraction,Database Management,
"Data Governance":["Compliance","Database Management","Policy Management","Risk Management"],
"Data Loss Prevention":["Backup","Business Continuity","Disk Imaging","Endpoint Protection","File Sync","Server Backup"],
"Data Management":["Data Governance","Database Management","Master Data Management"],
"Data Mining":["Big Data","Business Intelligence","Data Extraction"],
"Data Quality":["Big Data","Business Intelligence","Contact Management","Data Governance","Lead Management","Master Data Management"],
"Data Visualization":["Business Intelligence","Business Performance Management","Embedded Analytics","Reporting"],
"Data Warehouse":["Big Data","Business Continuity","Business Intelligence","Data Analysis","Database Management"],
"Database Management":["Business Continuity","Data Center Management","Data Entry","RDBMS"],
"Debt Collection":["Accounting","Billing and Invoicing"],
"Decision Support":["Business Intelligence","Business Performance Management","Risk Management"],
"Deep Learning":["Artificial Intelligence","Big Data","Machine Learning","Predictive Analytics"],
"Delivery Management":["Courier","Fleet Management","Food Delivery","Freight","Logistics","Route Planning","Transportation Dispatch"],
"Demand Planning":["MRP","Retail Management Systems","Sales Forecasting","Supply Chain Management"],
"Dental":["Dental Charting","Dental Imaging","Electronic Medical Records","Medical Billing","Medical Practice Management","Medical Scheduling","Medical Transcription"],
"Dental Charting":["Dental","Dental Imaging","Electronic Medical Records"],
"Dental Imaging":["Dental","Dental Charting","Electronic Medical Records","PACS"],
"Dermatology":["Electronic Medical Records","Medical Billing","Medical Imaging","Medical Lab","Medical Practice Management","Medical Scheduling","Plastic Surgery"],
"DevOps":["App Design","Application Development","Continuous Integration","IT Management","IT Project Management"],
"Diagram":["Artificial Intelligence","Business Process Management","Data Visualization","Idea Management","Presentation","Wireframe","Workflow Management"],
"Digital Adoption Platform":["Customer Experience","Customer Success","Digital Workplace","Knowledge Management"],
"Digital Asset Management":["Brand Management","Content Management","Document Management","Marketing Automation"],
"Digital Rights Management":["Content Management","Document Control","Intellectual Property Management","License Management","Subscription Management","Video Management"],
"Digital Signage":["Android Kiosk","Kiosk","iPad Kiosk"],
"Digital Signature":["Contract Management","Document Management","Forms Automation","Proposal Management"],
"Digital Workplace":["Business Process Management","Cloud Management","Collaboration","File Sharing","Project Management","Robotic Process Automation","Space Management","Task Management","Team Communication","Unified Communications","Web Conferencing","Workflow Management","Workforce Management"],
"Disk Imaging":["Backup","Business Continuity"],
"Distribution":["Food Service Distribution","Freight","Inventory Management","Logistics","Shipping","Supply Chain Management","Warehouse Management"],
"Dock Scheduling":["Courier","Delivery Management","Freight","Logistics","Scheduling","Shipping","Transportation Management","Warehouse Management","Yard Management"],
"Docketing":["Court Management","Intellectual Property Management","Law Practice Management","Legal Calendar","Legal Case Management"],
"Document Control":["Compliance","Document Management","Legal Document Management"],
"Document Generation":["Contract Management","Data Entry","Document Control","Document Management","Document Version Control","Forms Automation","Legal Document Management"],
"Document Management":["Content Management","Digital Asset Management","Forms Automation","Legal Document Management","Proposal Management"],
"Document Version Control":["Document Control","Document Management","Legal Document Management"],
"Donation Management":["Association Management","Church Management","Fund Accounting","Fundraising","Membership Management","Nonprofit","Political Campaign"],
"Driving School":["Appointment Scheduling","Tutoring"],
"Dry Cleaning":["Point of Sale","Retail Management Systems"],
"EAM":["Asset Tracking","Budgeting","Fixed Asset Management","IT Asset Management"],
"EDI":["Banking Systems","Integration"],
"EHS Management":["Emissions Management","Environmental","Ergonomics","Facility Management","Quality Management"],
"EMS,Electronic Medical Records,
"ETL":["Big Data","Data Discovery","Data Entry","Data Extraction","Data Management","Data Mining","Data Quality","Database Management","Master Data Management"],
"Electrical Contractor,Field Service Management,
"Electrical Design":["3D CAD","Architectural CAD","Diagram","Electrical Contractor","Electrical Estimating","Engineering CAD","Flowchart","Wireframe"],
"Electrical Estimating":["Construction Estimating","Electrical Contractor","HVAC Estimating","Plumbing Estimating","Remodeling Estimating","Residential Construction Estimating"],
"Electronic Data Capture":["Clinical Trial Management","Data Extraction","Document Management"],
"Electronic Discovery":["Document Management","Email Management","Law Enforcement","Law Practice Management","Legal Case Management","Legal Document Management","Legal Trial Presentation"],
"Electronic Medical Records":["Chiropractic","Dental","Dental Charting","Dental Imaging","Hospital Management","Long Term Care","Medical Billing","Medical Practice Management","Medical Scheduling","Medical Transcription","Mental Health","Patient Case Management","Patient Management"],
"Email Archiving":["Archiving","Compliance","Data Governance","Electronic Discovery","Email Management"],
"Email Management":["Electronic Discovery","Email Marketing","IT Management"],
"Email Marketing":["Campaign Management","Contact Management","Customer Relationship Management","Marketing Automation","Survey"],
"Email Security":["Anti-spam","Cloud Security","Computer Security","Email Archiving","Email Management","Email Marketing","Email Signature","Email Tracking","Email Verification Tools","Network Security"],
"Email Signature":["Campaign Management","Email Management"],
"Email Tracking":["Campaign Management","Email Marketing","Sales Force Automation"],
"Email Verification Tools":["Data Quality","Email Management","Email Marketing","Email Security","Email Tracking"],
"Embedded Analytics":["Business Intelligence","Data Visualization","Integration","Reporting"],
"Emergency Notification":["Business Continuity","Compliance","EHS Management","EMS","Incident Management","Risk Management","Safety Management"],
"Emissions Management":["Compliance","EHS Management","Environmental","Waste Management"],
"Employee Communication Tools":["Benefits Administration","Employee Engagement","Employee Recognition","Human Resource","Internal Communications","Intranet","Team Communication"],
"Employee Engagement":["Community","Gamification","Human Resource","Learning Experience Platform","Survey","Talent Management"],
"Employee Monitoring":["Computer Security","Human Resource","Network Security","Productivity","Time Clock"],
"Employee Recognition":["Community","Human Resource","Performance Appraisal","Talent Management"],
"Employee Scheduling":["Scheduling","Workforce Management"],
"Endpoint Protection":["Computer Security","Endpoint Detection and Response","Identity Management","Mobile Device Management","Mobility","Network Security","Password Management"],
"Energy Management":["Building Maintenance","Facility Management","Utility Billing"],
"Engineering CAD":["3D CAD","Architectural CAD","Simulation"],
"Enterprise Architecture":["Application Development","Change Management","Diagram","IT Management","Innovation","Integration","IoT","Risk Management","Strategic Planning"],
"Enterprise Content Management":["Content Management","Enterprise Search","Java CMS","Mobile Content Management System"],
"Enterprise Resource Planning":["Accounting","Business Performance Management","Distribution","Human Resource","Inventory Management","Logistics","MRP","Project Management","Supply Chain Management","Warehouse Management","Workforce Management"],
"Enterprise Search":["Artificial Intelligence","Enterprise Content Management","Personalization","eCommerce"],
"Environmental":["Compliance","EHS Management","Emissions Management"],
"Equipment Maintenance":["Aviation Maintenance","Building Maintenance","CMMS","Fleet Maintenance","HVAC","Maintenance Management","Service Dispatch","Work Order"],
"Equity Management":["Accounting","Compensation Management","Fund Accounting","Fundraising","Hedge Fund","Human Resource","Investment Management","Stock Portfolio Management"],
"Event Booking":["Conference","Event Management","Registration","Ticketing"],
"Event Check In":["Conference","Event Management","Kiosk","Registration","Ticketing","Venue Management"],
"Event Management":["Catering","Conference","Event Check In","Meeting","Registration","Ticketing","Venue Management"],
"Event Marketing":["Campaign Management","Content Marketing","Email Marketing","Event Booking","Event Check In","Event Management","Influencer Marketing","Landing Page","Marketing Analytics","Marketing Attribution","Marketing Automation","Marketing Planning","Mobile Marketing","Registration","SMS Marketing","Social Media Marketing","Ticketing","Website Builder"],
"Exam":["Classroom Management","Learning Management System","School Administration","Training"],
"Expense Report":["Accounting","Accounts Payable","Time Tracking","Time and Expense"],
"Facility Management":["Building Maintenance","Ergonomics","Maintenance Management","Meeting","Scheduling","Venue Management","Visitor Management"],
"Farm Management":["Equipment Maintenance","Forestry","Garden Center","Horse","Inventory Management","Winery"],
"Fashion Design,Apparel Management,
"Fax Server":["Email Management","Server Management","Unified Communications"],
"Festival Management":["Event Management","Registration","Ticketing","Venue Management"],
"Field Service Management":["HVAC","Maid Service","Maintenance Management","Plumbing","Service Dispatch","Work Order"],
"File Sharing":["Collaboration","Content Management","Document Management","Portal"],
"File Sync":["Backup","Business Continuity","Collaboration","Disk Imaging","File Sharing"],
"Financial CRM":["Banking Systems","Customer Relationship Management","Hedge Fund","Investment Banking","Investment Management"],
"Financial Fraud Detection":["Banking Systems","Financial Risk Management","Hedge Fund","Investment Management"],
"Financial Management":["Accounting","Billing and Invoicing","Budgeting","Financial Reporting","Financial Risk Management","Financial Services","Fund Accounting","Revenue Management"],
"Financial Reporting":["Accounting","Accounting Practice Management","Audit","Budgeting","Business Intelligence","Business Performance Management","Compliance","Reporting","Sales Tax"],
"Financial Risk Management":["Banking Systems","Financial Fraud Detection","Investment Management","Risk Management"],
"Financial Services":["AML","Accounting","Accounting Practice Management","Commercial Loan","Financial CRM","Financial Fraud Detection","Financial Management","Financial Reporting","Financial Risk Management","Mortgage and Loans","Professional Services Automation"],
"Fire Department":["EMS","Law Enforcement"],
"Fitness":["Club Management","Personal Trainer"],
"Fixed Asset Management":["Accounting","Equipment Maintenance","IT Asset Management","Inventory Control"],
"Fleet Maintenance":["Aviation Maintenance","Equipment Maintenance","Fleet Management","Maintenance Management","Trucking","Work Order"],
"Fleet Management":["Equipment Maintenance","Fleet Maintenance","Maintenance Management","Towing","Transportation Dispatch","Transportation Management","Trucking"],
"Florist":["Garden Center","Point of Sale","Retail Management Systems"],
"Flowchart":["Business Intelligence","Business Process Management","Data Visualization","Diagram","Human Resource","Reporting"],
"Food Delivery":["Restaurant Management","Restaurant POS"],
"Food Service Distribution":["Catering","Distribution","Food Service Management","Restaurant Management"],
"Food Service Management":["Catering","Food Service Distribution","Nutrition Analysis","Restaurant Management"],
"Food Traceability":["Barcoding","EHS Management","Farm Management","Food Service Distribution","Food Service Management","Inventory Control","Quality Management"],
"Forestry,Farm Management,
"Forms Automation":["Business Process Management","Content Management","Contract Management","Document Management","Survey"],
"Franchise Management":["Retail Management Systems","eCommerce"],
"Freight":["Fleet Management","Fuel Management","Logistics","Shipping","Supply Chain Management","Transportation Dispatch","Transportation Management","Trucking"],
"Fuel Management":["Fleet Management","Oil and Gas","Trucking"],
"Fund Accounting":["Accounting","Accounting Practice Management","Church Management","Donation Management","Fundraising","Government","Nonprofit","School Accounting","Trust Accounting"],
"Fundraising":["Donation Management","Fund Accounting","Membership Management","Nonprofit","Political Campaign"],
"Funeral Home,Cemetery,
"GDPR Compliance":["Compliance","PCI Compliance","Risk Management"],
"GPS Tracking":["Asset Tracking","Fleet Management","Workforce Management"],
"GRC":["Audit","Compliance","Financial Risk Management","Integrated Risk Management","Risk Management","Strategic Planning"],
"Game Development":["Application Development","Artificial Intelligence","Augmented Reality","Gamification","VR"],
"Gamification":["Call Center","Community","Contest","Customer Engagement","Employee Engagement","Learning Experience Platform","Learning Management System","Performance Appraisal","Sales Enablement","Training","VR"],
"Gantt Chart":["Agile Project Management Tools","Diagram","Flowchart","IT Project Management","Kanban Tools","Project Management","Project Portfolio Management","Project Tracking","Scrum","Spreadsheet"],
"Garage Door":["Appointment Scheduling","Billing and Invoicing","Employee Scheduling","Field Service Management","Route Planning","Service Dispatch"],
"Garden Center":["Farm Management","Florist","Point of Sale","Retail Management Systems"],
"Golf Course":["Club Management","Membership Management"],
"Government":["Code Enforcement","Fund Accounting","Law Enforcement","Political Campaign","Public Works"],
"Gradebook":["Classroom Management","School Administration"],
"Grant Management":["Fund Accounting","Fundraising","Nonprofit"],
"Graphic Design":["Presentation","Web to Print"],
"Gymnastics":["Club Management","Dance Studio","Martial Arts","Membership Management","Sports League","Waiver","Yoga Studio"],
"HOA":["Association Management","Membership Management","Real Estate Property Management"],
"HR Analytics":["Business Intelligence","Human Resource","Predictive Analytics","Statistical Analysis","Succession Planning","Talent Management","Workforce Management"],
"HVAC":["Building Maintenance","Equipment Maintenance","Field Service Management","Maintenance Management","Service Dispatch"],
"HVAC Estimating":["Construction Estimating","Field Service Management","HVAC"],
"Handyman":["Appointment Scheduling","Billing and Invoicing","Field Service Management","HVAC","Plumbing","Professional Services Automation","Roofing"],
"Healthcare CRM":["Electronic Medical Records","Hospital Management","Medical Practice Management"],
"Heatmap":["Business Intelligence","Data Visualization","Web Analytics"],
"Hedge Fund":["Banking Systems","Financial Risk Management","Investment Management"],
"Help Desk":["Call Center","Complaint Management","Customer Relationship Management","Customer Service","ITSM","Issue Tracking","Knowledge Management","Live Chat","Online CRM"],
"Higher Education":["Admissions","Classroom Management","Gradebook","Grant Management","Scholarship Management","School Accounting","School Administration"],
"Home Builder":["3D Architecture","3D CAD","Architectural CAD","Architecture","Construction Accounting","Construction CRM","Construction Estimating","Construction Management","Remodeling Estimating","Residential Construction Estimating"],
"Home Care,Home Health Care,
"Home Health Care":["Assisted Living","Home Care","Human Services","Long Term Care","Patient Case Management"],
"Home Inspection,Inspection,
"Horse":["Farm Management","Veterinary"],
"Hospice":["Assisted Living","Electronic Medical Records","Home Health Care","Hospital Management"],
"Hospital Management":["Electronic Medical Records","Long Term Care","Medical Practice Management","Patient Case Management","Patient Management"],
"Hospitality Property Management":["Guest Management","Real Estate Property Management","Rental","Reservations"],
"Hostel Management":["Guest Management","Hospitality Property Management","Reservations","Vacation Rental"],
"Hotel Channel Management":["Channel Management","Distribution","Guest Management","Hospitality Property Management","Hostel Management","Reservations","Vacation Rental"],
"Human Resource":["360 Degree Feedback","Benefits Administration","Compensation Management","Ergonomics","Onboarding","Payroll","Performance Appraisal","Reference Check","Succession Planning","Talent Management","Workforce Management"],
"Human Services":["Mental Health","Patient Case Management"],
"IT Asset Management":["Fixed Asset Management","IT Management","SaaS Management"],
"IT Management":["Business Continuity","IT Asset Management","Network Monitoring","Network Security","SaaS Management","Website Monitoring"],
"IT Project Management":["Application Development","Collaboration","Diagram","IT Management","Idea Management","Professional Services Automation","Project Management","Project Portfolio Management","Requirements Management","Resource Management","Task Management","Time Tracking","Time and Expense","Wireframe","Workflow Management"],
"IT Service":["ITSM","MSP","Service Dispatch"],
"ITSM":["Complaint Management","Help Desk","IT Service","Issue Tracking"],
"IVR":["Call Center","Speech Recognition","Survey"],
"IWMS":["Building Maintenance","Facility Management","IT Asset Management","IT Management","Lease Management","Meeting","Space Management","Work Order"],
"Idea Management":["Collaboration","Diagram","IT Project Management","Project Management"],
"Identity Management":["Computer Security","Physical Security","Visitor Management"],
"Incident Management":["Bug Tracking","Business Continuity","Compliance","EHS Management","Help Desk","Physical Security","Risk Management","Safety Management"],
"Influencer Marketing":["Brand Management","Campaign Management","Content Marketing","Marketing Automation","Social Media Management","Social Media Marketing","Social Media Monitoring"],
"Innovation":["Change Management","Idea Management"],
"Inside Sales":["Predictive Dialer","Sales Force Automation"],
"Inspection":["Code Enforcement","Field Service Management","Food Service Management","Government"],
"Insurance Agency":["Commercial Insurance","Commission","Insurance Policy","Insurance Rating"],
"Insurance Policy":["Claims Processing","Commercial Insurance","Insurance Agency","Insurance Rating"],
"Insurance Rating":["Claims Processing","Commercial Insurance","Insurance Agency","Insurance Policy"],
"Integrated Risk Management":["Audit","Business Continuity","Compliance","Data Governance","Financial Risk Management","GDPR Compliance","GRC","PCI Compliance","Risk Management"],
"Integration":["Application Development","Embedded Analytics"],
"Intellectual Property Management":["Law Practice Management","Legal Document Management"],
"Internal Communications":["Collaboration","Community","Employee Engagement","Human Resource","Social Networking"],
"Intranet":["Collaboration","Community","Employee Engagement","Portal","Social Networking"],
"Inventory Control":["Barcoding","Inventory Management","Retail Management Systems","Warehouse Management"],
"Inventory Management":["Barcoding","Distribution","Inventory Control","Order Management","Supply Chain Management","Warehouse Management"],
"Investigation Management":["Law Enforcement","Legal Case Management"],
"Investment Management":["Banking Systems","Hedge Fund"],
"IoT":["Application Development","Artificial Intelligence","Big Data","Cloud Management","Endpoint Detection and Response","Integration","Predictive Analytics"],
"Issue Tracking":["Bug Tracking","Complaint Management","Help Desk","Project Management"],
"Janitorial":["Carpet Cleaning","Facility Management","Hospitality Property Management","Maid Service"],
"Java CMS":["Content Management","Enterprise Content Management","Mobile Content Management System"],
"Jewelry Store Management":["Inventory Control","Point of Sale","Retail Management Systems"],
"Job Board":["Applicant Tracking","Recruiting","Reference Check","Talent Management"],
"Job Costing":["Construction Estimating","Construction Management","Manufacturing","Manufacturing Execution","Print Estimating","Professional Services Automation","Project Management","Quoting"],
"Job Evaluation":["Human Resource","Recruiting","Succession Planning","Talent Management"],
"Job Shop":["MRP","Manufacturing Execution"],
"K-12":["Child Care","Classroom Management","Gradebook","Learning Management System","School Accounting","School Administration","Student Information System"],
"Kanban Tools":["Agile Project Management Tools","App Design","Application Development","DevOps","Game Development","Gantt Chart","IT Project Management","Project Management","Project Tracking","Scrum"],
"Kennel,Veterinary,
"Kiosk":["Android Kiosk","Digital Signage","Order Entry","Photo Booth","Retail Management Systems","Ticketing","iPad Kiosk"],
"Knowledge Management":["Content Management","Digital Adoption Platform","Portal"],
"Laboratory Information Management System":["Data Analysis","Data Quality","Medical Inventory","Medical Lab","Statistical Analysis"],
"Land Management":["Government","Inspection","Oil and Gas","Permit"],
"Landing Page":["AB Testing","Email Marketing","Lead Management","Marketing Automation","SMS Marketing","Sales Enablement"],
"Landscape":["Construction Management","Field Service Management","Garden Center","Lawn Care"],
"Law Enforcement":["Government","Investigation Management","Jail Management","Legal Case Management"],
"Law Practice Management":["Court Management","Legal Billing","Legal Calendar","Legal Case Management","Legal Document Management","Trust Accounting"],
"Lawn Care":["Field Service Management","Garden Center","Landscape"],
"Lead Capture":["Conference","Customer Relationship Management","Data Extraction","Electronic Data Capture","Event Management","Landing Page","Lead Generation","Lead Management","Sales Force Automation","Telemarketing"],
"Lead Generation":["Account Based Marketing","Lead Management","Marketing Automation","Referral","Sales Force Automation"],
"Lead Management":["Channel Management","Commission","Contact Management","Customer Relationship Management","Quoting","Referral","Sales Force Automation"],
"Lead Nurturing":["Campaign Management","Customer Communications Management","Customer Engagement","Lead Capture","Lead Generation","Lead Management","Marketing Automation","Personalization","Sales Force Automation","Transactional Email"],
"Learning Experience Platform":["Augmented Reality","Course Authoring","Employee Engagement","Gamification","Learning Management System","Microlearning","Mobile Learning","Student Engagement Platform","Training","VR"],
"Learning Management System":["Course Authoring","Learning Experience Platform","Mobile Learning","School Administration","Talent Management","Training","eLearning Authoring Tools"],
"Lease Accounting":["Accounting","Accounting Practice Management","Lease Management"],
"Lease Management":["Contract Management","Hospitality Property Management","Real Estate Property Management","Rental"],
"Leave Management System":["Attendance Tracking","Benefits Administration","Human Resource","Time Tracking"],
"Legal Billing":["Law Practice Management","Legal Case Management","Time Tracking","Time and Expense","Trust Accounting"],
"Legal Calendar":["Court Management","Law Practice Management","Legal Billing","Legal Case Management"],
"Legal Case Management":["Court Management","Electronic Discovery","Investigation Management","Law Enforcement","Law Practice Management","Legal Billing","Legal Calendar","Legal Document Management"],
"Legal Document Management":["Court Management","Document Management","Electronic Discovery","Law Practice Management","Legal Case Management","Waiver"],
"Library Automation":["Church Management","Nonprofit","School Administration"],
"License Management":["Application Lifecycle Management","IT Asset Management","IT Management","Network Monitoring","SaaS Management"],
"Link Management Tools":["Campaign Management","Content Management","Marketing Analytics","Marketing Attribution","Marketing Automation","SEO"],
"Live Chat":["Customer Service","Help Desk","Online CRM","Sales Enablement"],
"Load Balancing":["Network Monitoring","Server Management","Website Monitoring"],
"Loan Origination":["Commercial Loan","Loan Servicing","Mortgage and Loans"],
"Loan Servicing":["Commercial Loan","Loan Origination","Mortgage and Loans"],
"Location Intelligence":["Business Intelligence","GIS","Sales Force Automation","Store Locator"],
"Log Management":["IT Management","Network Monitoring","Server Management","Website Monitoring"],
"Logbook":["CMMS","Employee Scheduling","Facility Management","Fleet Management","Maintenance Management"],
"Logistics":["Distribution","Enterprise Resource Planning","Food Service Distribution","Freight","Inventory Management","Shipping","Supply Chain Management","Trucking","Warehouse Management"],
"Long Term Care":["Assisted Living","Electronic Medical Records","Hospital Management","Medical Billing","Medical Practice Management","Medical Scheduling"],
"Lost and Found":["Business Management","Event Management","Hospitality Property Management","Municipal","Vacation Rental"],
"MLM":["Distribution","Marketing Automation","Sales Force Automation"],
"MRM":["Marketing Automation","Marketing Planning"],
"MRP":["Enterprise Resource Planning","Ergonomics","Manufacturing Execution","Production Scheduling"],
"MSP":["IT Management","IT Service","ITSM"],
"Mac CRM":["Construction CRM","Customer Relationship Management","Financial CRM","Online CRM","Real Estate CRM"],
"Machine Learning":["Artificial Intelligence","Big Data","Deep Learning","Robotic Process Automation"],
"Maid Service":["Carpet Cleaning","Facility Management","Field Service Management","Hospitality Property Management","Janitorial","Service Dispatch"],
"Mailroom Management":["Facility Management","Shipping"],
"Maintenance Management":["Aviation Maintenance","Building Maintenance","CMMS","Equipment Maintenance","Field Service Management","Fleet Maintenance","Service Dispatch","Work Order"],
"Manufacturing":["MRP","Manufacturing Execution","Production Scheduling"],
"Manufacturing Execution":["MRP","Production Scheduling"],
"Market Research":["Customer Satisfaction","Survey"],
"Marketing Analytics":["Business Intelligence","Marketing Automation","Marketing Planning","Predictive Analytics"],
"Marketing Attribution":["MRM","Marketing Analytics","Marketing Automation","Marketing Planning"],
"Marketing Automation":["Account Based Marketing","Brand Management","Campaign Management","Channel Management","Content Marketing","Customer Relationship Management","Digital Asset Management","Email Marketing","Lead Management","Push Notifications","Web Analytics"],
"Marketing Planning":["Budgeting","Business Plan","MRM","Marketing Automation","Sales Forecasting"],
"Marketplace":["Multi-Channel eCommerce","Small Business eCommerce","Vendor Management","Website Builder","eCommerce"],
"Martial Arts":["Club Management","Membership Management","Waiver"],
"Massage Therapy":["Medical Spa","Salon","Spa"],
"Master Data Management":["Data Governance","Data Management","PIM","Product Data Management"],
"Medical Billing":["Chiropractic","Claims Processing","Dental","Electronic Medical Records","Hospital Management","Medical Practice Management","Medical Scheduling","Mental Health"],
"Medical Imaging":["Dental Imaging","PACS"],
"Medical Inventory":["Chiropractic","Dental","Hospital Management","Inventory Control","Inventory Management","Medical Practice Management","Optometry"],
"Medical Lab":["Electronic Medical Records","Medical Billing","Medical Practice Management"],
"Medical Practice Management":["Chiropractic","Dental","Electronic Medical Records","Hospital Management","Medical Billing","Medical Scheduling","Medical Transcription","Mental Health","Optometry","Patient Case Management","Patient Management","Pediatric","Waiver"],
"Medical Scheduling":["Chiropractic","Dental","Electronic Medical Records","Hospital Management","Long Term Care","Medical Billing","Medical Practice Management","Mental Health"],
"Medical Spa":["Salon","Spa","Waiver"],
"Medical Transcription":["Chiropractic","Dental","Electronic Medical Records","Hospital Management","Long Term Care","Medical Practice Management","Mental Health","Speech Recognition"],
"Meeting":["Event Management","Facility Management","Scheduling"],
"Meeting Room Booking System":["Board Management","Event Booking","IWMS","Meeting","Reservations","Resource Management","Space Management"],
"Membership Management":["Association Management","Church Management","Club Management","Fundraising","Nonprofit"],
"Mental Health":["Electronic Medical Records","Hospital Management","Medical Billing","Medical Practice Management","Medical Scheduling","Medical Transcription","Patient Case Management","Patient Management"],
"Mentoring":["Human Resource","Performance Appraisal"],
"Microlearning":["Course Authoring","Employee Engagement","Employee Recognition","Gamification","Learning Experience Platform","Learning Management System","Mobile Learning","Training"],
"Mind Mapping":["Diagram","Flowchart","Idea Management","Innovation","Knowledge Management"],
"Mining":["GIS","Oil and Gas"],
"Mobile Analytics":["Business Intelligence","Customer Engagement","Customer Experience","Marketing Automation","Web Analytics"],
"Mobile Banking":["Banking Systems","Online Banking"],
"Mobile Content Management System":["Content Management","Enterprise Content Management","Java CMS"],
"Mobile Credit Card Processing":["Payment Processing","iPad POS"],
"Mobile Device Management":["Endpoint Detection and Response","IT Asset Management","IT Management","Mobility","Wireless Expense Management"],
"Mobile Learning":["Course Authoring","Learning Experience Platform","Learning Management System","Talent Management","Training"],
"Mobile Marketing":["App Design","Customer Engagement","Marketing Automation","Mobile Analytics","Mobile Content Management System","Personalization","SMS Marketing"],
"Mobility":["Application Development","Application Lifecycle Management","Mobile Device Management"],
"Mortgage and Loans":["Commercial Loan","Loan Origination","Loan Servicing"],
"Moving,Trucking,
"Multi-Channel eCommerce":["Small Business eCommerce","eCommerce"],
"Municipal":["Code Enforcement","Government","Public Works"],
"Museum":["Art Gallery","Donation Management","Fundraising","Membership Management","Nonprofit"],
"Music School,Membership Management,
"Network Mapping":["Diagram","Network Monitoring","Network Security"],
"Network Monitoring":["Application Performance Management","Computer Security","Data Center Management","Endpoint Detection and Response","IT Management","Network Security"],
"Network Security":["Computer Security","Endpoint Detection and Response","IT Management","Network Monitoring"],
"Network Troubleshooting":["Issue Tracking","Network Monitoring"],
"Nonprofit":["Association Management","Church Management","Donation Management","Fund Accounting","Fundraising","Membership Management"],
"Nonprofit Accounting":["Accounting","Accounting Practice Management","Bookkeeper","Church Accounting","Donation Management","Financial Reporting","Fund Accounting","Nonprofit","Tax Practice Management"],
"Nonprofit CRM":["Construction CRM","Customer Relationship Management","Financial CRM","Healthcare CRM","Mac CRM","Nonprofit","Nonprofit Accounting","Online CRM","Real Estate CRM"],
"Nursing Home":["Assisted Living","Electronic Medical Records","Long Term Care"],
"Nutrition Analysis":["Bakery","Catering","Food Service Management","Nutritionist","Personal Trainer","Restaurant Management"],
"Nutritionist":["Medical Practice Management","Nutrition Analysis","Personal Trainer"],
"OCR":["Billing and Invoicing","Document Control","Document Management","Document Version Control","Enterprise Search","Expense Report","Legal Document Management","PDF","Physical Security","Visitor Management"],
"OEE":["Equipment Maintenance","IoT","Manufacturing","Manufacturing Execution","Quality Management","Work Order"],
"OKR":["Business Intelligence","Business Performance Management","Dashboard","Performance Appraisal","Project Management","Reporting","Task Management"],
"Occupational Therapy":["Electronic Medical Records","Medical Practice Management","Physical Therapy","Speech Therapy"],
"Oil and Gas":["GIS","Mining"],
"Onboarding":["Applicant Tracking","Human Resource","Recruiting","Talent Management","Training"],
"Online Banking":["Banking Systems","Mobile Banking"],
"Online CRM":["Customer Relationship Management","Customer Service","Help Desk","Knowledge Management","Live Chat"],
"Online Proofing":["Advertising Agency","Creative Management","Digital Asset Management","Marketing Automation","Photography Studio"],
"Optometry":["Electronic Medical Records","Medical Billing"],
"Order Entry":["Android Kiosk","Catalog Management","Order Management","Product Configurator","Retail Management Systems","iPad Kiosk"],
"Order Management":["Inventory Management","Logistics","Order Entry"],
"Org Chart":["Diagram","Human Resource","Strategic Planning","Succession Planning","Talent Management","Workforce Management"],
"P&C Insurance":["Claims Processing","Commercial Insurance","Insurance Agency","Insurance Policy","Insurance Rating"],
"PACS":["Dental Imaging","Hospital Management","Medical Practice Management","Radiology"],
"PCI Compliance":["AML","Compliance","Financial Fraud Detection","Financial Risk Management","Log Management","Mobile Credit Card Processing","Network Monitoring","Network Security","Payment Processing","Risk Management"],
"PDF":["Document Management","Productivity"],
"PIM":["Campaign Management","Catalog Management","Digital Asset Management","Distribution","Marketing Automation","Product Data Management","Product Management","Sales Enablement"],
"PPC":["Campaign Management","SEO","Web Analytics"],
"Packaging":["3D CAD","Freight","Graphic Design","Manufacturing","Shipping","Warehouse Management"],
"Parcel Audit":["Audit","Courier","Delivery Management","Freight","Logistics","Shipment Tracking","Shipping"],
"Parking Management":["Facility Management","Transportation Management"],
"Parks and Recreation":["Camp Management","Club Management","Facility Management"],
"Password Management":["Computer Security","Endpoint Protection","Identity Management"],
"Patch Management":["Application Lifecycle Management","Application Performance Management","Network Monitoring","Server Management","Website Monitoring"],
"Patient Case Management":["Electronic Medical Records","Medical Practice Management","Mental Health","Patient Management"],
"Patient Engagement":["Hospital Management","Medical Practice Management","Patient Case Management","Patient Management","Patient Portal","Personalization"],
"Patient Management":["Electronic Medical Records","Medical Practice Management","Mental Health","Patient Case Management"],
"Patient Portal":["Medical Billing","Medical Practice Management","Medical Scheduling","Patient Management"],
"Pawn Shop":["Consignment","Point of Sale"],
"Payment Processing":["Billing and Invoicing","Point of Sale","Restaurant POS"],
"Payroll":["Attendance Tracking","Benefits Administration","Compensation Management","Human Resource","Workforce Management"],
"Pediatric":["Electronic Medical Records","Medical Billing","Medical Practice Management","Medical Scheduling"],
"Performance Appraisal":["360 Degree Feedback","Employee Recognition","Human Resource","Mentoring","Talent Management"],
"Performance Testing":["AB Testing","Application Performance Management","Automated Testing","Load Balancing","Website Monitoring"],
"Permit":["Construction Management","Construction Scheduling","Government","Land Management","Municipal"],
"Personal Trainer":["Club Management","Ergonomics","Fitness","Nutrition Analysis"],
"Personalization":["AB Testing","Account Based Marketing","Artificial Intelligence","Big Data","Customer Experience","Predictive Analytics","Push Notifications","eCommerce"],
"Pest Control":["Facility Management","Field Service Management","Service Dispatch"],
"Pet Grooming,Kennel,
"Pet Sitting":["Kennel","Veterinary"],
"Pharmacy":["Hospital Management","Long Term Care","Medical Practice Management"],
"Photography Studio,Photo Booth,
"Physical Security":["Facility Management","Visitor Management"],
"Physical Therapy":["Ergonomics","Medical Practice Management","Occupational Therapy","Speech Therapy"],
"Pilates Studio":["Club Management","Membership Management","Waiver","Yoga Studio"],
"Plastic Surgery":["Dermatology","Electronic Medical Records","Medical Billing","Medical Imaging","Medical Inventory","Medical Lab","Medical Practice Management","Medical Scheduling","Medical Spa"],
"Plumbing":["Field Service Management","Service Dispatch"],
"Plumbing Estimating":["Construction Estimating","Field Service Management","Plumbing"],
"Podiatry":["Dermatology","Electronic Medical Records","Medical Billing","Medical Imaging","Medical Inventory","Medical Lab","Medical Practice Management","Medical Scheduling","Medical Spa","Medical Transcription"],
"Point of Sale":["Garden Center","Jewelry Store Management","Payment Processing","Restaurant POS","Retail Management Systems","Retail POS System","Salon","Spa","iPad POS"],
"Policy Management":["Compliance","Risk Management"],
"Political Campaign":["Fundraising","Government","Volunteer Management"],
"Polling":["Survey","Voting"],
"Pool Service":["Appointment Scheduling","Billing and Invoicing","Business Management","Employee Scheduling","Field Service Management","Route Planning","Service Dispatch"],
"Portal":["Board Management","Collaboration","Knowledge Management","Social Networking"],
"Pre-employment Testing":["Applicant Tracking","Human Resource","Recruiting","Reference Check","Talent Management"],
"Predictive Analytics":["Artificial Intelligence","Big Data","Business Intelligence","Data Visualization","Decision Support","Reporting","Sales Forecasting","Text Mining"],
"Predictive Dialer":["Call Center","Call Recording","Inside Sales"],
"Presentation":["Document Management","Sales Enablement"],
"Preventive Maintenance":["Aviation Maintenance","Building Maintenance","CMMS","EAM","Equipment Maintenance","Fixed Asset Management","Fleet Maintenance","Maintenance Management"],
"Pricing Optimization,Retail Management Systems,
"Print Estimating,Quoting,
"Privileged Access Management":["Authentication","Computer Security","Identity Management","Network Security"],
"Procurement":["Accounting","Contract Management","Purchasing","Sourcing","Supply Chain Management","Vendor Management"],
"Product Configurator":["Catalog Management","MRP","Order Entry","Production Scheduling","Quoting","eCommerce"],
"Product Data Management":["Catalog Management","MRP","Manufacturing Execution","Product Configurator","Product Lifecycle Management"],
"Product Lifecycle Management":["Application Lifecycle Management","Product Data Management","Project Management","Requirements Management","Task Management"],
"Product Management":["Product Lifecycle Management","Product Roadmap","Project Management","Requirements Management"],
"Product Roadmap":["Product Lifecycle Management","Product Management","Project Management"],
"Production Scheduling":["MRP","Manufacturing Execution"],
"Productivity":["Business Management","Document Management","Task Management"],
"Professional Services Automation":["Accounting Practice Management","Contract Management","Project Management","Proposal Management","Time and Expense","Workflow Management"],
"Project Management":["Collaboration","IT Project Management","Idea Management","Professional Services Automation","Project Portfolio Management","Requirements Management","Resource Management","Task Management","Time Tracking","Time and Expense","Workflow Management"],
"Project Planning":["Agile Project Management Tools","Construction Estimating","Construction Management","Construction Scheduling","Enterprise Resource Planning","Gantt Chart","IT Project Management","Kanban Tools","MRP","Marketing Planning","Project Management","Project Portfolio Management","Project Tracking","Residential Construction Estimating","Resource Management","Scrum","Strategic Planning"],
"Project Portfolio Management":["Professional Services Automation","Project Management","Resource Management","Task Management"],
"Project Tracking":["IT Project Management","Project Management","Project Portfolio Management","Resource Management","Task Management","Workforce Management"],
"Proofreading":["Content Management","Content Marketing","Digital Rights Management","Document Management","Enterprise Content Management","Legal Document Management","Mobile Content Management System","Productivity"],
"Proposal Management":["CPQ","Contract Management","Digital Signature","Document Management","Professional Services Automation","Quoting","Sales Enablement"],
"Prototyping":["AB Testing","App Design","Engineering CAD","Simulation","Wireframe"],
"Public Relations,Campaign Management,
"Public Transportation":["Fleet Management","Transportation Dispatch","Transportation Management"],
"Public Works":["Facility Management","Government","Maintenance Management","Quality Management","Service Dispatch","Utility Billing"],
"Publishing and Subscriptions":["Catalog Management","Digital Asset Management","Subscription Management"],
"Punch List":["Construction Accounting","Construction Estimating","Construction Management"],
"Purchasing":["Accounting","Contract Management","Procurement","Vendor Management"],
"Push Notifications":["Customer Engagement","Marketing Automation","Personalization"],
"Qualitative Data Analysis":["Customer Experience","Data Analysis","Statistical Analysis","UX"],
"Quality Management":["Compliance","MRP","Product Lifecycle Management"],
"Quoting":["CPQ","Contract Management","Job Costing","Product Configurator","Proposal Management","Sales Force Automation"],
"RDBMS":["Data Entry","Database Management"],
"RFP":["Contract Management","Document Generation","Document Version Control","Forms Automation","Procurement","Proposal Management","Sourcing","Supply Chain Management","Vendor Management"],
"Radiology,Medical Practice Management,
"Real Estate Agency":["Commercial Real Estate","Lease Management","Real Estate CMA","Real Estate CRM","Real Estate Property Management","Real Estate Transaction Management"],
"Real Estate CMA":["Commercial Real Estate","Real Estate Agency","Real Estate CRM","Real Estate Property Management","Real Estate Transaction Management"],
"Real Estate CRM":["Commercial Real Estate","Contact Management","Customer Relationship Management","Hospitality Property Management","Lead Management","Lease Management","Mac CRM","Marketing Automation","Real Estate Agency","Real Estate CMA","Real Estate Property Management","Real Estate Transaction Management","Rental Property Management","Sales Force Automation","Vacation Rental"],
"Real Estate Property Management":["Commercial Real Estate","HOA","Hospitality Property Management","Lease Management","Real Estate Agency","Real Estate CMA","Real Estate CRM","Real Estate Transaction Management","Rental Property Management","Vacation Rental"],
"Real Estate Transaction Management":["Commercial Real Estate","Real Estate Agency","Real Estate CMA","Real Estate CRM","Real Estate Property Management"],
"Recruiting":["Applicant Tracking","Human Resource","Job Board","Pre-employment Testing","Reference Check","Talent Management","Video Interviewing"],
"Recruiting Agency":["Applicant Tracking","Job Board","Recruiting","Reference Check","Video Interviewing"],
"Recurring Billing":["Accounting","Accounts Receivable","Billing and Invoicing","Debt Collection","Legal Billing","Medical Billing","Publishing and Subscriptions","Subscription Management"],
"Recycling":["Environmental","Waste Management"],
"Reference Check":["Applicant Tracking","Background Check","Human Resource","Job Board","Pre-employment Testing","Recruiting","Recruiting Agency","Staffing Agency","Talent Management","Video Interviewing"],
"Referral":["Affiliate","Customer Reference Management","Lead Management","Marketing Automation"],
"Registration":["Event Management","Reservations"],
"Relocation":["Benefits Administration","Digital Workplace","Employee Communication Tools","Human Resource","IWMS","Moving","Space Management","Vendor Management","Workforce Management"],
"Remodeling Estimating":["Architecture","Construction Estimating","Home Builder","Residential Construction Estimating","Roofing"],
"Remote Support":["Call Center","Complaint Management","Customer Relationship Management","Customer Service","Help Desk","ITSM","Issue Tracking","Knowledge Management","Live Chat","Online CRM"],
"Rental":["Car Rental","Vacation Rental"],
"Rental Property Management":["HOA","Lease Management","Real Estate Property Management","Vacation Rental"],
"Reporting":["Business Intelligence","Business Performance Management","Data Visualization","Embedded Analytics","Financial Reporting"],
"Reputation Management":["Brand Management","Social Networking"],
"Requirements Management":["Product Lifecycle Management","Project Management","Task Management"],
"Reservations":["Airline Reservation System","Appointment Scheduling","Guest Management","Hospitality Property Management","Registration","Restaurant Management","Tour Operator","Travel Agency"],
"Residential Construction Estimating":["Architecture","Construction Estimating","Home Builder","Remodeling Estimating","Roofing"],
"Resource Management":["Demand Planning","Employee Scheduling","Enterprise Resource Planning","Ergonomics","Marketing Planning","Professional Services Automation","Project Management","Project Planning","Project Portfolio Management","Workforce Management"],
"Restaurant Management":["Catering","Food Service Management","Nutrition Analysis","Restaurant POS"],
"Restaurant POS":["Food Service Management","Point of Sale","Restaurant Management","iPad POS"],
"Retail Management Systems":["Inventory Control","Kiosk","Point of Sale","Retail POS System","Store Locator","eCommerce"],
"Retail POS System":["Point of Sale","Retail Management Systems","iPad POS"],
"Retargeting":["Ad Server","Campaign Management","Marketing Attribution","Marketing Automation","Mobile Marketing","Social Media Marketing"],
"Revenue Management":["Accounting","Accounts Receivable","Financial Management","Hospitality Property Management","Pricing Optimization","Pricing Optimization","Reservations"],
"Review Management":["Brand Management","Customer Experience","Customer Loyalty","Customer Satisfaction","Reputation Management"],
"Risk Management":["Audit","Business Intelligence","Compliance","Ergonomics","Financial Risk Management","GRC","Integrated Risk Management","Strategic Planning"],
"Robotic Process Automation":["Artificial Intelligence","Business Process Management","Conversational AI Platform","Digital Workplace","Machine Learning"],
"Roofing":["Construction Estimating","Field Service Management","Home Builder","Remodeling Estimating","Residential Construction Estimating"],
"Route Planning":["Courier","Field Service Management","Fleet Management","Service Dispatch","Transportation Dispatch","Trucking"],
"SEO":["Campaign Management","Content Marketing","Marketing Automation","Web Analytics"],
"SIEM":["Computer Security","Cybersecurity","Endpoint Detection and Response","Endpoint Protection","Log Management","Network Monitoring","Network Security","Vulnerability Management"],
"SMS Marketing":["Channel Management","Email Marketing","Marketing Automation"],
"SPC":["Manufacturing Execution","Quality Management"],
"SaaS Management":["360 Degree Feedback","Application Lifecycle Management","Application Performance Management","IT Asset Management","IT Management","License Management","Subscription Management"],
"Safety Management":["Compliance","Corrective and Preventive Action","EHS Management","Training"],
"Sales Coaching":["Onboarding","Sales Enablement","Training","Tutoring"],
"Sales Enablement":["Customer Relationship Management","Inside Sales","Lead Management","Marketing Automation","Proposal Management","Sales Force Automation"],
"Sales Force Automation":["Contact Management","Customer Relationship Management","Inside Sales","Lead Management","Marketing Automation","Quoting","Sales Enablement"],
"Sales Forecasting":["Business Intelligence","Data Visualization","Decision Support","Reporting","Sales Force Automation"],
"Sales Tax":["Accounting","Accounting Practice Management","Bookkeeper","Financial Reporting"],
"Salon":["Appointment Scheduling","Medical Spa","Spa"],
"Scheduling":["Appointment Scheduling","Employee Scheduling","Facility Management","Medical Scheduling","Meeting"],
"Scholarship Management":["Admissions","School Administration"],
"School Accounting":["Accounting Practice Management","Fund Accounting","Fundraising","School Administration"],
"School Administration":["Admissions","Classroom Management","Gradebook","Scholarship Management","School Accounting"],
"School Bus Routing":["Fleet Management","Public Transportation","Route Planning","School Administration","Transportation Dispatch"],
"Scrum":["Agile Project Management Tools","App Design","Application Development","DevOps","Game Development","Gantt Chart","IT Project Management","Kanban Tools","Project Management","Project Tracking"],
"Security System Installer":["Field Service Management","Physical Security"],
"Self Storage,Rental,
"Server Backup":["Backup","Business Continuity","Server Management","Virtual Machine"],
"Server Management":["Data Center Management","Load Balancing","Network Monitoring","Patch Management","Virtualization","Website Monitoring"],
"Service Desk":["Cybersecurity","Help Desk","ITSM","MSP"],
"Service Dispatch":["Field Service Management","Transportation Dispatch"],
"Shipment Tracking":["Courier","Delivery Management","Freight","Logistics","Multi-Channel eCommerce","Order Management","Parcel Audit","Retail Management Systems","Shipping","Small Business eCommerce","Warehouse Management","eCommerce"],
"Shipping":["Courier","Distribution","Freight","Logistics","Mailroom Management","Supply Chain Management","Transportation Dispatch","Warehouse Management"],
"Shopping Cart":["Retail Management Systems","eCommerce"],
"Simulation":["3D CAD","Engineering CAD","VR"],
"Single Sign On":["Authentication","Identity Management","Password Management"],
"Small Business CRM":["Business Management","Construction CRM","Customer Communications Management","Customer Relationship Management","Financial CRM","Healthcare CRM","Mac CRM","Nonprofit CRM","Online CRM","Real Estate CRM","Small Business Loyalty Programs","Small Business eCommerce","Social CRM Tools"],
"Small Business Loyalty Programs":["Customer Loyalty","Small Business eCommerce"],
"Small Business eCommerce":["Multi-Channel eCommerce","Small Business Loyalty Programs","eCommerce"],
"Social CRM Tools":["Construction CRM","Conversational Marketing Platform","Customer Communications Management","Customer Engagement","Customer Relationship Management","Financial CRM","Healthcare CRM","Influencer Marketing","Mac CRM","Nonprofit CRM","Online CRM","Real Estate CRM","Small Business CRM","Social Media Marketing","Social Media Monitoring","Social Networking"],
"Social Media Analytics Tools":["Content Marketing","Influencer Marketing","Marketing Analytics","Marketing Attribution","Social CRM Tools","Social Media Management","Social Media Marketing","Social Media Monitoring","Social Selling"],
"Social Media Management":["Public Relations","Reputation Management","Social Media Marketing"],
"Social Media Marketing":["Campaign Management","Marketing Automation","Reputation Management","Social Media Management"],
"Social Media Monitoring":["Reputation Management","Social Media Management","Social Media Marketing"],
"Social Networking":["Collaboration","Community","Membership Management"],
"Social Work Case Management":["Human Services","Legal Case Management","Patient Case Management"],
"Softphone":["Call Center","Mobility","Telephony","VoIP"],
"Source Code Management":["App Design","Application Development","Change Management","Continuous Integration","DevOps","Game Development","IT Asset Management","IT Project Management"],
"Sourcing":["Contract Management","Procurement","Purchasing","Supply Chain Management","Vendor Management"],
"Spa":["Hospitality Property Management","Medical Spa","Salon"],
"Space Management":["Ergonomics","Facility Management","Resource Management","Workforce Management"],
"Speech Recognition":["IVR","Medical Transcription"],
"Speech Therapy":["Electronic Medical Records","Medical Practice Management","Occupational Therapy","Physical Therapy"],
"Sports League":["Club Management","Membership Management","Registration","Waiver"],
"Spreadsheet":["Collaboration","Data Visualization","Financial Reporting","Productivity","Reporting"],
"Staffing Agency":["Applicant Tracking","Background Check","Credentialing","Human Resource","Onboarding","Pre-employment Testing","Recruiting","Recruiting Agency","Reference Check","Video Interviewing"],
"Statistical Analysis":["Business Intelligence","Data Visualization","Qualitative Data Analysis","Reporting"],
"Stock Portfolio Management":["Financial Reporting","Hedge Fund","Investment Management"],
"Store Locator":["GIS","Retail Management Systems","eCommerce"],
"Strategic Planning":["Business Performance Management","Business Plan","OKR","Risk Management"],
"Student Engagement Platform":["Alumni Management","Audience Response","Community","Higher Education","K-12","Learning Analytics","Learning Experience Platform","Learning Management System","Mobile Learning","Polling","Presentation","Social Networking","Student Information System","Survey","Training","Voting"],
"Student Information System":["Higher Education","Learning Management System","School Administration"],
"Subscription Management":["Digital Rights Management","Publishing and Subscriptions","Recurring Billing","SaaS Management"],
"Succession Planning":["Human Resource","Talent Management","Training","Workforce Management"],
"Supply Chain Management":["Distribution","Enterprise Resource Planning","Freight","Inventory Management","Logistics","Shipping","Warehouse Management"],
"Survey":["360 Degree Feedback","Customer Experience","IVR","Market Research"],
"Sustainability":["Complaint Management","EHS Management","Environmental","Government","Recycling","Waste Management"],
"Swim School":["Club Management","Membership Management","Sports League","Waiver"],
"Takeoff":["Construction Estimating","Construction Management","Job Costing"],
"Talent Management":["360 Degree Feedback","Applicant Tracking","Compensation Management","Employee Engagement","Employee Recognition","Human Resource","Learning Management System","Onboarding","Performance Appraisal","Recruiting","Reference Check","Succession Planning","Training"],
"Task Management":["Project Management","Requirements Management","Time and Expense","Workflow Management"],
"Tattoo Studio":["Appointment Scheduling","Salon"],
"Tax Practice Management":["Accounting","Accounting Practice Management","Bookkeeper","Professional Services Automation"],
"Team Communication":["Collaboration","Community","File Sharing","Live Chat","Project Management","Social Networking","Web Conferencing"],
"Telecom Expense Management":["Call Accounting","Call Recording","Telephony","Wireless Expense Management"],
"Telemarketing":["Call Center","Inside Sales","Predictive Dialer"],
"Telemedicine":["Electronic Medical Records","Home Health Care","Medical Practice Management","Mental Health","Web Conferencing"],
"Telephony":["Call Accounting","Call Center","IVR","Telecom Expense Management","VoIP"],
"Text Mining":["Big Data","Business Intelligence","Content Marketing","Customer Experience","Data Extraction"],
"Ticketing":["Android Kiosk","Event Management","Registration","Venue Management","iPad Kiosk"],
"Time Clock":["Attendance Tracking","Human Resource","Payroll","Time Tracking","Workforce Management"],
"Time Tracking":["Billing and Invoicing","Legal Billing","Professional Services Automation","Project Management","Time Clock","Time and Expense"],
"Time and Expense":["Billing and Invoicing","Expense Report","Professional Services Automation","Project Management","Time Tracking"],
"Timeshare":["Hospitality Property Management","Vacation Rental"],
"Tool Management":["Construction Management","Equipment Maintenance","Field Service Management"],
"Tour Operator":["Reservations","Travel Agency"],
"Towing":["Fleet Management","Service Dispatch","Transportation Dispatch","Trucking"],
"Trade Promotion Management":["Marketing Planning","Pricing Optimization","Revenue Management"],
"Training":["Course Authoring","Ergonomics","Human Resource","Learning Experience Platform","Learning Management System","VR","Workforce Management","eLearning Authoring Tools"],
"Transactional Email":["Campaign Management","Email Archiving","Email Management","Email Marketing","Email Security","Email Signature","Email Tracking","Email Verification Tools","Marketing Automation","Personalization"],
"Translation Management":["Business Management","Content Management","Professional Services Automation","Website Builder"],
"Transportation Dispatch":["Field Service Management","Service Dispatch","Trucking"],
"Transportation Management":["Fleet Maintenance","Fleet Management","Logistics","Supply Chain Management","Transportation Dispatch","Trucking"],
"Travel Agency":["Airline Reservation System","Reservations","Tour Operator","Travel Management"],
"Travel Management":["Expense Report","Policy Management","Reservations","Time and Expense"],
"Treasury":["Accounting","Budgeting","Financial Reporting","Financial Risk Management","Hedge Fund"],
"Trucking":["Fleet Management","Freight","Logistics","Moving","Towing","Transportation Dispatch","Transportation Management"],
"Trust Accounting":["Accounting","Accounting Practice Management","Fund Accounting","Investment Management","Law Practice Management"],
"Tutoring":["Classroom Management","School Administration"],
"UX":["Diagram","Graphic Design","Qualitative Data Analysis","Wireframe"],
"Unified Communications":["Collaboration","Mobility","Telephony","VoIP","Web Conferencing"],
"Utility Billing":["Billing and Invoicing","Energy Management","Government","Utility Management Systems"],
"Utility Management Systems,Utility Billing,
"VPN":["Computer Security","Endpoint Protection","Network Security"],
"VR":["Application Development","Augmented Reality","Game Development","Gamification","Learning Experience Platform","Simulation","Training","Virtual Tour"],
"Vacation Rental":["Guest Management","Hospitality Property Management","Real Estate Property Management","Rental","Timeshare"],
"Vector Graphics":["Fashion Design","Graphic Design","Web to Print"],
"Vendor Management":["Contract Management","Procurement","Proposal Management","Purchasing"],
"Venue Management":["Event Management","Facility Management","Ticketing"],
"Veterinary":["Farm Management","Horse","Kennel"],
"Video Editing,Video Management,
"Video Interviewing":["Applicant Tracking","Recruiting","Recruiting Agency","Reference Check","Staffing Agency"],
"Video Making":["Augmented Reality","Graphic Design","VR","Video Editing","Video Interviewing","Video Management","Video Marketing","Virtual Tour"],
"Video Management":["Digital Asset Management","Video Editing"],
"Virtual Data Room":["Document Management","Electronic Data Capture"],
"Virtual Machine":["Backup","IT Asset Management","IT Management","Virtualization"],
"Virtual Tour":["Augmented Reality","Higher Education","Photography Studio","Presentation","Real Estate Agency","Sales Enablement","VR"],
"Virtualization":["IT Management","Server Management"],
"Visitor Management":["Facility Management","Identity Management"],
"Visual Search":["Artificial Intelligence","Customer Engagement","Deep Learning","Digital Asset Management","Enterprise Search","Image Recognition","Machine Learning","Multi-Channel eCommerce","Personalization","Product Configurator","Product Data Management","Retail Management Systems","Small Business eCommerce","eCommerce"],
"VoIP":["Call Accounting","Call Center","IVR","Telecom Expense Management","Telephony"],
"Volunteer Management":["Church Management","Donation Management","Event Management","Nonprofit","Political Campaign"],
"Voting":["Political Campaign","Polling","Survey"],
"Vulnerability Management":["Computer Security","Endpoint Detection and Response","Endpoint Protection","Network Monitoring","Network Security","Risk Management"],
"Waitlist":["Appointment Reminder","Appointment Scheduling","Barbershop","Class Registration","Medical Practice Management","Medical Spa","Pet Grooming","Registration","Restaurant Management","Salon","Spa"],
"Waiver":["Dance Studio","Digital Signature","Gymnastics","Legal Document Management","Martial Arts","Medical Practice Management","Medical Spa","Pilates Studio","Sports League","Swim School","Yoga Studio"],
"Warehouse Management":["Distribution","Inventory Management","Logistics","Order Management","Supply Chain Management"],
"Warranty Management":["Auto Dealer","Auto Repair","Computer Repair Shop","Construction Management","Contract Management","Field Service Management","Home Builder","IT Service","Inventory Control","Inventory Management","Manufacturing","Product Lifecycle Management","Product Management","Retail Management Systems"],
"Waste Management":["EHS Management","Facility Management","Public Works","Service Dispatch"],
"Web Analytics":["AB Testing","Campaign Management","Lead Management","Marketing Automation","Website Monitoring"],
"Web Conferencing":["Collaboration","Meeting"],
"Web to Print":["Order Management","Print Estimating","eCommerce"],
"Webinar":["Collaboration","Meeting","Presentation","Training","Web Conferencing"],
"Website Builder":["Content Management","Landing Page"],
"Website Monitoring":["Load Balancing","Network Monitoring","Network Security"],
"Website Optimization Tools":["AB Testing","SEO","Web Analytics","Website Monitoring"],
"Winery":["Farm Management","Point of Sale","Retail Management Systems"],
"Wireframe":["Application Development","Diagram"],
"Wireless Expense Management":["Call Accounting","Call Recording","Telecom Expense Management","Telephony"],
"Work Order":["Building Maintenance","Equipment Maintenance","Field Service Management","Fleet Maintenance","Maintenance Management","Service Dispatch"],
"Workflow Management":["Business Process Management","Professional Services Automation","Project Management","Requirements Management"],
"Workforce Management":["Call Center","Ergonomics","Human Resource","Payroll","Performance Appraisal","Talent Management","Time Clock"],
"Worship":["Church Management","Church Presentation"],
"Yard Management":["Fleet Management","Logistics","Manufacturing","Transportation Management","Warehouse Management"],
"Yoga Studio":["Club Management","Membership Management","Pilates Studio","Waiver"],
"Zoo":["Animal Shelter","Farm Management","Museum"],
"e-Prescribing":["Electronic Medical Records","Hospital Management","Medical Practice Management"],
"eCommerce":["Auction","Catalog Management","Content Management","Inventory Management","Multi-Channel eCommerce","Order Entry","Order Management","Point of Sale","Product Configurator","Retail Management Systems","Small Business eCommerce"],
"eLearning Authoring Tools":["Course Authoring","Learning Management System","Training"],
"iPad Kiosk":["Android Kiosk","Digital Signage","Kiosk","Order Entry","Photo Booth","Ticketing","iPad POS"],
"iPad POS":["Bar POS","Point of Sale","Restaurant POS","Retail POS System","iPad Kiosk"],
"GIS":[""],
"Marine":[""]}
